const String ASSERT = 'assert';
const String BREAK = 'break';
const String CASE = 'case';
const String CONST = 'const';
const String CONTINUE = 'continue';
const String DEFAULT = 'default';
const String ELSE = 'else';
const String FALSE = 'false';
const String FINAL = 'final';
const String FOR = 'for';
const String IF = 'if';
const String ITERATE = 'iterate';
const String NULL = 'null';
const String RETURN = 'return';
const String SWITCH = 'switch';
const String STATIC = 'static'; // TODO: implement
const String TRUE = 'true';
const String WHILE = 'while';
